name = "blob-ezpz-sh"
main = "api/index.js"
compatibility_date = "2026-01-27"
workers_dev = false

routes = [ { pattern = "blob.ezpz.sh/*", zone_name = "ezpz.sh" } ]

[assets]
directory = "ui"

[[r2_buckets]]
binding = "FILES"
bucket_name = "files"

[[kv_namespaces]]
binding = "AUTH"
id = "bfb2b2405536457f9d54c2a2993cb0aa"

[vars]
PUBLIC_PREFIX = "pub/"
RESTRICTED_PREFIX = "priv/"
POLICY_KEY = "config/policy.json"
CACHE_SECONDS = "0"
